### ISSUE TITLE
不支持php7.2，希望更新

### ISSUE THREAD

**Issue by lang-longmao** [baolan-zifu/BlueWE_MT#1]
在最新核心上运行会有很多的报错，而且貌似没有设置点的指令

**Comment by Takaranoao** [comment]
您好，可否提供报错的详细内容？

**Comment by lang-longmao** [comment]
太多的报错以致难以上传，比如插件无法加载，修好这个后执行指令又会报错...所以很难说明有哪些

**Comment by Takaranoao** [comment]
嗯，我传错版本了，现在还在检查有没有漏掉的东西。已更新。
